### ISSUE TITLE
Question about the meaning of datasets

### ISSUE THREAD

**Issue by WtaoZhao** [Graph-COM/StruRW#1]
Hi, I have downloaded the files test_gg_PU30.root and test_qq_PU30.root from your provided link, https://zenodo.org/record/8015774. I am considering training my model using the data in test_gg_PU30 and testing it on the data in test_qq_PU30. However, I am unsure about the meaning of "gg" and "qq." Could you kindly provide a brief introduction to these terms? This information would greatly help me in describing them appropriately in my paper. Thank you very much for your assistance.

**Comment by WtaoZhao** [comment]
Furthermore, could you please provide details about the training and testing data used for the experiment "gg → Z(vv)" mentioned in Table 4 of your paper? Thank you for your kind assistance.

**Comment by sallylsk** [comment]
Hello, thanks for the clarification questions!
1). The meaning of "gg" and "qq"
A: They are two different signal processes in generating the leading collisions in these physics events
2). The datasets used for experiment "gg->Z(vv)"
A: We use the test_Znunu_PU50.root and test_gg_PU50.root in this case
