### ISSUE TITLE
Question about the experiment on arxiv dataset

### ISSUE THREAD

**Issue by BonitoW** [Graph-COM/StruRW#2]
Hi, thanks for your work! I have a question about how you prepare the Arxiv dataset for the experiment. In your code, you select all nodes whose year is less than year_bound[1] to build the target/source domain graph, and set those with year > year_bound[0] to build the test mask in each domain. In your experiment, the target domain contains nodes before 2020, and the source domain contains nodes before 2011/2007. Does this mean that the target domain actually contains all the nodes in the source domain?

**Comment by sallylsk** [comment]
Thanks for the question! The testing points for the target domain only contain the samples in between the selected year bound, but the graph contains all the nodes before the year_bound[1], so as the nodes in the source domain. The preprocessing code is adopted from https://github.com/qitianwu/GraphOOD-EERM/blob/e757002ff1f7f9b0306b37dd65b5c72adeadd38b/temp_arxiv/dataset.py.
