### ISSUE TITLE
The code stucked into starting nni server and can't add expriment

### ISSUE THREAD

**Issue by rrc693** [Graph-COM/StruRW#3]
![image](https://github.com/Graph-COM/StruRW/assets/68151037/b27cb389-d209-47ee-a366-f2d6794b625b)
There is not any error , but the expriment can't be added in nni expriment when I try to conduct your code(Stru-RW ERM).
Specifically, the code trapped into expriment.run()
![image](https://github.com/Graph-COM/StruRW/assets/68151037/6d2a31bf-1d84-4d46-833b-a4869dcf3efa)
 
Parameters are --name ERM -d cora -m ERM -b GCN --port 10700 --dir_name 
How can I solve this problem, and what caused it

**Comment by sallylsk** [comment]
Thanks for your interest in our work! I’m wondering have you added the argument for the dir_name since the later training code requires this argument. Thanks!
